/**
 * Build the browser half: client/index.jsx → client/client.js.
 *
 * The DSH browser module system loads a plugin bundle as a lazily materialized
 * CommonJS factory registered through `window.__ModuleLoader__.load`, and the
 * registration id must equal the package name the host put in the boot graph.
 * React stays external because the shell seeds it into the frozen module
 * table; anything else would be a second React instance and break hooks.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const sourceDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(sourceDir, '..');
const manifest = JSON.parse(await readFile(resolve(packageRoot, 'package.json'), 'utf8'));
const outputPath = resolve(packageRoot, 'client/client.js');

const result = await build({
  entryPoints: [resolve(sourceDir, 'index.jsx')],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: ['chrome100'],
  jsx: 'automatic',
  // Only the platform seed table may be requested; React's JSX runtime is the
  // single external this bundle uses.
  external: ['react', 'react/jsx-runtime'],
  define: { __DSH_VK1_PET_VERSION__: JSON.stringify(manifest.version) },
  write: false,
  minify: process.env.NODE_ENV === 'production',
  legalComments: 'none',
});

const bundled = result.outputFiles?.[0]?.text;
if (bundled === undefined) throw new Error('esbuild produced no client bundle');

const wrapped = `// Generated by client/build.mjs from client/index.jsx — do not edit by hand.
window.__ModuleLoader__.load({
  id: ${JSON.stringify(manifest.name)},
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
${bundled}
    return module.exports;
  },
});
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, wrapped, 'utf8');
console.log(`Wrote ${outputPath} (${Buffer.byteLength(wrapped)} bytes)`);
