// Generated by client/build.mjs from client/index.jsx — do not edit by hand.
window.__ModuleLoader__.load({
  id: "dsh-vk1-pet",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name2 in all)
    __defProp(target, name2, { get: all[name2], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// client/index.jsx
var index_exports = {};
__export(index_exports, {
  apply: () => apply,
  inject: () => inject,
  name: () => name
});
module.exports = __toCommonJS(index_exports);
var import_react = require("react");

// client/constants.js
var BASE_PATH = "/dsh-vk1-pet";
var TABLET_WIDTH = 400;
var TABLET_HEIGHT = 220;
var ARTWORK_WIDTH = 1536;
var CHARACTERS = [
  {
    id: "deepseek",
    title: "\u84DD\u8272\u5927\u80A5\u9C7C",
    file: "sprite.png",
    offlineFile: "sprite-deepseek-offline.png",
    corners: { tl: [1060, 699], tr: [1413, 644], bl: [1090, 889] }
  },
  {
    id: "gpt",
    title: "GPT\u9F99\u5A18",
    file: "sprite-gpt.png",
    corners: { tl: [1060, 699], tr: [1413, 644], bl: [1090, 889] }
  },
  {
    id: "claude",
    title: "\u5927\u5C0F\u59D0Claude",
    file: "sprite-claude.png",
    corners: { tl: [1060, 699], tr: [1413, 644], bl: [1090, 889] }
  },
  {
    id: "gemini",
    title: "\u5317\u7F8E\u732B\u5A18Gemini",
    // Gemini's right fingers reach farther into the screen, so the text safe
    // area is narrower to clear them.
    file: "sprite-gemini.png",
    corners: { tl: [1065, 699], tr: [1400, 646], bl: [1095, 889] }
  }
];
var SIZE_PRESETS = [
  { id: "small", title: "\u5C0F", side: 110 },
  { id: "medium", title: "\u4E2D", side: 150 },
  { id: "large", title: "\u5927", side: 210 },
  { id: "huge", title: "\u7279\u5927", side: 280 }
];
var INTERVAL_CHOICES = [10, 30, 60, 300];
var SNAP_POSITION = { left: 12, bottom: 12 };
function releasePosition(drag, snapOnRelease) {
  if (drag === null || drag === void 0 || drag.moved !== true) return null;
  if (snapOnRelease) return SNAP_POSITION;
  return drag.last ?? { left: drag.originLeft, bottom: drag.originBottom };
}
var SOURCE_CHOICES = [
  { id: "auto", title: "\u81EA\u52A8" },
  { id: "api-key", title: "API Key" },
  { id: "account", title: "DSH \u8D26\u53F7" }
];
function characterOf(id) {
  return CHARACTERS.find((entry) => entry.id === id) ?? CHARACTERS[0];
}
function sizeOf(id) {
  return SIZE_PRESETS.find((entry) => entry.id === id) ?? SIZE_PRESETS[1];
}
function spriteFileFor(character, connected) {
  return character.id === "deepseek" && !connected ? character.offlineFile : character.file;
}
function layoutOf(side) {
  const width = side * 1.5;
  const height = side * 1.55;
  const spriteWidth = side * 0.94 * 1.5;
  const spriteHeight = side * 0.94;
  const spriteLeft = (width - spriteWidth) / 2;
  const spriteTop = height - side * 0.03 - spriteHeight;
  return {
    side,
    width,
    height,
    spriteWidth,
    spriteHeight,
    spriteLeft,
    spriteTop,
    scale: spriteWidth / ARTWORK_WIDTH
  };
}
function tabletMatrix(layout, corners) {
  const { spriteLeft, spriteTop, scale } = layout;
  const [tlx, tly] = corners.tl;
  const [trx, trY] = corners.tr;
  const [blx, bly] = corners.bl;
  const a = (trx - tlx) / TABLET_WIDTH * scale;
  const b = (trY - tly) / TABLET_WIDTH * scale;
  const c = (blx - tlx) / TABLET_HEIGHT * scale;
  const d = (bly - tly) / TABLET_HEIGHT * scale;
  const e = spriteLeft + tlx * scale;
  const f = spriteTop + tly * scale;
  return `matrix(${a}, ${b}, ${c}, ${d}, ${e}, ${f})`;
}
function assetUrl(name2) {
  const version = true ? "1.0.0" : "0";
  return `${BASE_PATH}/assets/${name2}?v=${encodeURIComponent(version)}`;
}
function fenToString(fen) {
  if (fen === null || fen === void 0 || !Number.isFinite(fen)) return "--";
  const negative = fen < 0;
  const magnitude = Math.abs(Math.round(fen));
  const fraction = magnitude % 100;
  return `${negative ? "-" : ""}${Math.floor(magnitude / 100)}.${String(fraction).padStart(2, "0")}`;
}

// client/api.js
var REQUEST_TIMEOUT_MS = 15e3;
async function request(path, init = {}) {
  const response = await fetch(`${BASE_PATH}${path}`, {
    credentials: "same-origin",
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
    headers: { accept: "application/json", ...init.body === void 0 ? {} : { "content-type": "application/json" } },
    ...init
  });
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  const body = await response.json();
  if (body === null || typeof body !== "object" || body.ok !== true) {
    throw new Error(typeof body?.error === "string" ? body.error : "invalid response");
  }
  return body.state;
}
function fetchState() {
  return request("/api/state");
}
function requestRefresh() {
  return request("/api/refresh", { method: "POST", body: "{}" });
}
function updateSettings(patch) {
  return request("/api/settings", { method: "POST", body: JSON.stringify(patch) });
}

// client/model.js
var STEP_INTERVAL = 0.2;
var HIT_DURATION = 0.55;
var FLOAT_LIFETIME = 0.95;
var TOPUP_DURATION = 0.9;
var MAX_PENDING_STEPS = 400;
var MAX_DEMO_STEPS = 200;
var MAX_FLOAT_LABELS = 60;
function createModel() {
  return {
    /** Last reading the server returned. */
    realFen: null,
    /** Amount the tablet currently shows; trails `realFen` during a hit queue. */
    bookedFen: null,
    /** Queued real deductions, one fen each. */
    pendingSteps: 0,
    /** Queued rehearsal steps. */
    demoRemaining: 0,
    /** How much the rehearsal has subtracted so far. */
    demoOffset: 0,
    /** Countdown before the rehearsal snaps back to the real balance. */
    demoRestoreTime: 0,
    stepCooldown: 0,
    shakeTime: 0,
    flashTime: 0,
    topupTime: 0,
    floating: [],
    nextFloatId: 1,
    /** Increments once per hit so the caller can play the sound effect. */
    hits: 0
  };
}
function snapToReal(model) {
  model.bookedFen = model.realFen;
  model.pendingSteps = 0;
  model.demoRemaining = 0;
  model.demoOffset = 0;
  model.demoRestoreTime = 0;
  model.stepCooldown = 0;
}
function resetModel(model) {
  model.realFen = null;
  model.bookedFen = null;
  snapToReal(model);
  model.floating = [];
  model.shakeTime = 0;
  model.flashTime = 0;
  model.topupTime = 0;
}
function pushFloat(model, text, tone) {
  model.floating.push({ id: model.nextFloatId, text, tone, age: 0 });
  model.nextFloatId += 1;
  if (model.floating.length > MAX_FLOAT_LABELS) {
    model.floating.splice(0, model.floating.length - MAX_FLOAT_LABELS);
  }
}
function applyReading(model, fen, options = {}) {
  if (fen === null || fen === void 0 || !Number.isFinite(fen)) return { kind: "none" };
  const previousReal = model.realFen;
  model.realFen = fen;
  if (options.snap === true || model.bookedFen === null || previousReal === null) {
    snapToReal(model);
    return { kind: "snap" };
  }
  if (fen > previousReal) {
    const credit = fen - previousReal;
    snapToReal(model);
    model.topupTime = TOPUP_DURATION;
    pushFloat(model, `+${fenToString(credit)}`, "topup");
    return { kind: "topup", credit };
  }
  if (fen < model.bookedFen) {
    const steps = model.bookedFen - fen;
    if (steps > MAX_PENDING_STEPS) {
      snapToReal(model);
      return { kind: "snap-large" };
    }
    model.pendingSteps = steps;
    return { kind: "deduct", steps };
  }
  model.pendingSteps = 0;
  return { kind: "steady" };
}
function playDemo(model, times) {
  const count = Math.max(1, Math.min(Math.trunc(times) || 1, MAX_DEMO_STEPS));
  model.demoRemaining = Math.min(MAX_DEMO_STEPS, model.demoRemaining + count);
  model.demoRestoreTime = 0;
}
function tick(model, dt) {
  if (!Number.isFinite(dt) || dt < 0) return false;
  const elapsed = Math.min(dt, 0.1);
  model.shakeTime = Math.max(0, model.shakeTime - elapsed);
  model.flashTime = Math.max(0, model.flashTime - elapsed);
  model.topupTime = Math.max(0, model.topupTime - elapsed);
  for (const label of model.floating) label.age += elapsed;
  if (model.floating.length > 0) {
    model.floating = model.floating.filter((label) => label.age < FLOAT_LIFETIME);
  }
  if (model.demoRestoreTime > 0) {
    model.demoRestoreTime = Math.max(0, model.demoRestoreTime - elapsed);
    if (model.demoRestoreTime === 0) model.demoOffset = 0;
  }
  if (model.pendingSteps <= 0 && model.demoRemaining <= 0) {
    model.stepCooldown = Math.max(0, model.stepCooldown - elapsed);
    return false;
  }
  model.stepCooldown -= elapsed;
  if (model.stepCooldown > 1e-9) return false;
  model.stepCooldown = Math.max(0, model.stepCooldown + STEP_INTERVAL);
  if (model.pendingSteps > 0 && model.bookedFen !== null && model.realFen !== null && model.bookedFen > model.realFen) {
    model.bookedFen -= 1;
    model.pendingSteps -= 1;
  } else if (model.demoRemaining > 0) {
    model.demoRemaining -= 1;
    model.demoOffset += 1;
    if (model.demoRemaining === 0) model.demoRestoreTime = HIT_DURATION;
  } else {
    model.pendingSteps = 0;
    return false;
  }
  model.shakeTime = HIT_DURATION;
  model.flashTime = HIT_DURATION;
  pushFloat(model, "-0.01", "hit");
  model.hits += 1;
  return true;
}
function needsFrame(model) {
  return model.pendingSteps > 0 || model.demoRemaining > 0 || model.demoRestoreTime > 0 || model.floating.length > 0 || model.shakeTime > 0 || model.flashTime > 0 || model.topupTime > 0;
}
function displayedFen(model) {
  if (model.bookedFen === null) return null;
  const value = model.bookedFen - model.demoOffset;
  return Math.max(Math.min(0, model.bookedFen), value);
}
function impact(model) {
  if (model.shakeTime <= 0) return 0;
  const elapsed = HIT_DURATION - model.shakeTime;
  if (elapsed < 0.08) return Math.min(1, elapsed / 0.08);
  return Math.max(0, 1 - (elapsed - 0.08) / (HIT_DURATION - 0.08));
}
function shakeOffset(model, side) {
  if (model.shakeTime <= 0) return { x: 0, y: 0 };
  const elapsed = HIT_DURATION - model.shakeTime;
  const decay = Math.max(0, model.shakeTime / HIT_DURATION);
  const amplitude = Math.min(3.2, side * 0.025);
  return {
    x: Math.sin(elapsed * 24) * amplitude * decay,
    y: Math.cos(elapsed * 19) * amplitude * 0.875 * decay
  };
}

// client/styles.js
var STYLE_ID = "dsh-vk1-pet/styles";
var CLASS = {
  root: "vk1p-root",
  shake: "vk1p-shake",
  image: "vk1p-image",
  flash: "vk1p-flash",
  ring: "vk1p-ring",
  tablet: "vk1p-tablet",
  tabletTitle: "vk1p-tablet-title",
  tabletAmount: "vk1p-tablet-amount",
  tabletCurrency: "vk1p-tablet-currency",
  tabletNumber: "vk1p-tablet-number",
  tabletDot: "vk1p-tablet-dot",
  float: "vk1p-float",
  floatHit: "vk1p-float-hit",
  floatTopup: "vk1p-float-topup",
  menu: "vk1p-menu",
  menuHead: "vk1p-menu-head",
  menuTitle: "vk1p-menu-title",
  menuMeta: "vk1p-menu-meta",
  menuError: "vk1p-menu-error",
  menuSep: "vk1p-menu-sep",
  menuItem: "vk1p-menu-item",
  menuItemDisabled: "vk1p-menu-item-disabled",
  menuGroupLabel: "vk1p-menu-group-label",
  menuChips: "vk1p-menu-chips",
  menuChip: "vk1p-menu-chip",
  menuChipOn: "vk1p-menu-chip-on",
  menuChipOff: "vk1p-menu-chip-off",
  pill: "vk1p-pill",
  pillDot: "vk1p-pill-dot",
  pillHidden: "vk1p-pill-hidden"
};
var CSS = `
.${CLASS.root} {
  position: fixed;
  z-index: 30;
  pointer-events: none;
  user-select: none;
  -webkit-user-select: none;
  touch-action: none;
  cursor: grab;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC",
    "Hiragino Sans GB", "Microsoft YaHei", sans-serif;
}
.${CLASS.root}:active { cursor: grabbing; }
.${CLASS.root}[data-dragging="true"] { cursor: grabbing; }

.${CLASS.shake} {
  position: absolute;
  left: 0;
  top: 0;
  will-change: transform;
}

.${CLASS.image} {
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  display: block;
  pointer-events: none;
  -webkit-user-drag: none;
}

/* Source-atop tint: the sprite's own alpha becomes the mask, so the character's
   soft edge survives instead of the transparent background filling in. */
.${CLASS.flash} {
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  pointer-events: none;
  -webkit-mask-size: 100% 100%;
  mask-size: 100% 100%;
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
}

.${CLASS.ring} {
  position: absolute;
  border-radius: 50%;
  pointer-events: none;
}

.${CLASS.tablet} {
  position: absolute;
  left: 0;
  top: 0;
  transform-origin: 0 0;
  overflow: hidden;
  pointer-events: none;
}
.${CLASS.tabletTitle},
.${CLASS.tabletAmount} {
  position: absolute;
  white-space: nowrap;
}
.${CLASS.tabletTitle} {
  left: 0;
  right: 0;
  text-align: center;
  font-weight: 700;
  text-shadow: 1.5px 1.5px 1.5px rgba(0, 0, 0, 0.65);
}
.${CLASS.tabletAmount} {
  left: 50%;
  display: inline-flex;
  align-items: baseline;
  justify-content: center;
  font-weight: 700;
  font-variant-numeric: tabular-nums;
  text-shadow: 1.5px 1.5px 1.5px rgba(0, 0, 0, 0.65);
}
.${CLASS.tabletCurrency} { font-weight: 700; }
.${CLASS.tabletNumber} {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-weight: 700;
  font-variant-numeric: tabular-nums;
}
.${CLASS.tabletDot} {
  position: absolute;
  border-radius: 50%;
}

.${CLASS.float} {
  position: absolute;
  font-weight: 800;
  font-variant-numeric: tabular-nums;
  white-space: nowrap;
  pointer-events: none;
  will-change: transform, opacity;
}
.${CLASS.floatHit} { color: #ff3b30; }
.${CLASS.floatTopup} { color: #34c759; }

.${CLASS.menu} {
  position: fixed;
  z-index: 40;
  pointer-events: auto;
  box-sizing: border-box;
  width: 268px;
  max-height: min(560px, calc(100vh - 24px));
  overflow-y: auto;
  padding: 6px;
  border-radius: 14px;
  border: 1px solid var(--dsw-alias-border-l2, rgba(0, 0, 0, 0.12));
  background: var(--dsw-specific-menu, var(--dsw-alias-bg-layer-1, #ffffff));
  box-shadow: 0 12px 32px rgba(0, 0, 0, 0.18);
  color: var(--dsw-alias-label-primary, #1f2329);
  font-size: 13px;
  line-height: 18px;
  cursor: default;
}
.${CLASS.menuHead} { padding: 8px 10px 6px; }
.${CLASS.menuTitle} { font-weight: 600; }
.${CLASS.menuMeta} {
  color: var(--dsw-alias-label-tertiary, #8b93a1);
  font-size: 12px;
  word-break: break-all;
}
.${CLASS.menuError} { color: #ff3b30; font-size: 12px; word-break: break-all; }
.${CLASS.menuSep} {
  height: 1px;
  margin: 6px 4px;
  background: var(--dsw-alias-border-l2, rgba(0, 0, 0, 0.08));
}
.${CLASS.menuItem} {
  display: flex;
  align-items: center;
  gap: 8px;
  min-height: 30px;
  padding: 0 10px;
  border-radius: 8px;
  border: 0;
  width: 100%;
  box-sizing: border-box;
  text-align: left;
  font: inherit;
  color: inherit;
  background: transparent;
  cursor: pointer;
}
.${CLASS.menuItem}:hover {
  background: var(--dsw-alias-interactive-bg-hover, rgba(127, 127, 127, 0.12));
}
.${CLASS.menuItemDisabled},
.${CLASS.menuItemDisabled}:hover {
  color: var(--dsw-alias-label-tertiary, #8b93a1);
  background: transparent;
  cursor: default;
}
.${CLASS.menuGroupLabel} {
  padding: 8px 10px 2px;
  color: var(--dsw-alias-label-tertiary, #8b93a1);
  font-size: 11px;
  letter-spacing: 0.04em;
}
.${CLASS.menuChips} {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  padding: 4px 10px 8px;
}
.${CLASS.menuChip} {
  font: inherit;
  font-size: 12px;
  height: 26px;
  padding: 0 10px;
  border-radius: 999px;
  border: 1px solid var(--dsw-alias-border-l2, rgba(0, 0, 0, 0.14));
  background: transparent;
  color: inherit;
  cursor: pointer;
  white-space: nowrap;
}
.${CLASS.menuChipOn} {
  border-color: transparent;
  /* The official pairing: the brand fill flips to a near-white surface in the
     dark theme, so the text must come from the foreground token that flips with
     it. A literal #fff reads as white-on-white there. */
  background: var(--dsw-alias-button-primary-fill, var(--dsw-alias-brand-primary, #4d6bfe));
  color: var(--dsw-alias-label-primary-foreground, #fff);
}
.${CLASS.menuChipOff} { opacity: 0.55; cursor: default; }

.${CLASS.pill} {
  position: fixed;
  z-index: 30;
  pointer-events: auto;
  display: inline-flex;
  align-items: center;
  gap: 6px;
  height: 26px;
  padding: 0 10px;
  border-radius: 999px;
  border: 1px solid var(--dsw-alias-border-l2, rgba(0, 0, 0, 0.12));
  background: var(--dsw-specific-menu, var(--dsw-alias-bg-layer-1, #ffffff));
  box-shadow: 0 4px 14px rgba(0, 0, 0, 0.14);
  color: var(--dsw-alias-label-primary, #1f2329);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", sans-serif;
  font-size: 12px;
  font-variant-numeric: tabular-nums;
  cursor: pointer;
  opacity: 0.85;
  transition: opacity 0.15s ease;
}
.${CLASS.pill}:hover { opacity: 1; }
.${CLASS.pillHidden} { opacity: 0.45; }
.${CLASS.pillDot} {
  width: 7px;
  height: 7px;
  border-radius: 50%;
  flex: none;
}

@media (prefers-reduced-motion: reduce) {
  .${CLASS.pill} { transition: none; }
}
`;

// client/index.jsx
var name = "dsh-vk1-pet";
var inject = ["slots"];
var SLOT = "shell.overlay";
var STORAGE_PREFIX = "dsh-vk1-pet:v1:";
var POLL_INTERVAL_MS = 2e3;
var ALPHA_THRESHOLD = 24;
var MASK_WIDTH = 192;
var MASK_HEIGHT = 128;
var KEEP_VISIBLE = 60;
var PILL_ATTR = "data-dsh-vk1-pet-pill";
function readStored(key, fallback) {
  try {
    const raw = window.localStorage.getItem(STORAGE_PREFIX + key);
    if (raw === null) return fallback;
    const parsed = JSON.parse(raw);
    return parsed === null || parsed === void 0 ? fallback : parsed;
  } catch {
    return fallback;
  }
}
function writeStored(key, value) {
  try {
    window.localStorage.setItem(STORAGE_PREFIX + key, JSON.stringify(value));
  } catch {
  }
}
function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
}
function clampPosition(position, layout) {
  const maxLeft = Math.max(0, window.innerWidth - KEEP_VISIBLE);
  const maxBottom = Math.max(0, window.innerHeight - KEEP_VISIBLE);
  return {
    left: Math.round(clamp(position.left, KEEP_VISIBLE - layout.width, maxLeft)),
    bottom: Math.round(clamp(position.bottom, KEEP_VISIBLE - layout.height, maxBottom))
  };
}
function statusLabel(state) {
  if (state === null) return "\u8FDE\u63A5\u4E2D\u2026";
  if (state.status === "unconfigured") return "\u672A\u914D\u7F6E\u51ED\u8BC1";
  if (state.connected) return `\u5DF2\u8FDE\u63A5 \xB7 \xA5${state.display ?? "--"}`;
  return state.error ?? "\u79BB\u7EBF";
}
function dotColorOf(state) {
  if (state !== null && state.connected) return "#34c759";
  if (state === null) return "#ffcc00";
  if (state.status === "unconfigured") return "#ff3b30";
  return state.error === null ? "#ffcc00" : "#ff3b30";
}
function MenuItem({ disabled = false, title, onSelect, children }) {
  return (0, import_react.createElement)("button", {
    type: "button",
    title,
    disabled,
    className: `${CLASS.menuItem}${disabled ? ` ${CLASS.menuItemDisabled}` : ""}`,
    onClick: disabled ? void 0 : (event) => {
      event.stopPropagation();
      onSelect();
    }
  }, children);
}
function ChipRow({ label, options, value, onSelect }) {
  return (0, import_react.createElement)(
    "div",
    null,
    (0, import_react.createElement)("div", { className: CLASS.menuGroupLabel }, label),
    (0, import_react.createElement)("div", { className: CLASS.menuChips }, options.map((option) => (0, import_react.createElement)("button", {
      key: option.id,
      type: "button",
      title: option.title,
      disabled: option.disabled === true,
      className: `${CLASS.menuChip}${option.id === value ? ` ${CLASS.menuChipOn}` : ""}${option.disabled === true ? ` ${CLASS.menuChipOff}` : ""}`,
      onClick: option.disabled === true ? void 0 : (event) => {
        event.stopPropagation();
        onSelect(option.id);
      }
    }, option.title)))
  );
}
function MenuShell({ point, onClose, children }) {
  const ref = (0, import_react.useRef)(null);
  (0, import_react.useEffect)(() => {
    const onDown = (event) => {
      if (ref.current !== null && ref.current.contains(event.target)) return;
      if (event.target instanceof Element && event.target.closest(`[${PILL_ATTR}]`) !== null) return;
      onClose();
    };
    const onKey = (event) => {
      if (event.key === "Escape") onClose();
    };
    document.addEventListener("pointerdown", onDown, true);
    document.addEventListener("keydown", onKey, true);
    return () => {
      document.removeEventListener("pointerdown", onDown, true);
      document.removeEventListener("keydown", onKey, true);
    };
  }, [onClose]);
  const style = {
    left: clamp(point.x, 8, Math.max(8, window.innerWidth - 276)),
    pointerEvents: "auto"
  };
  if (point.y > window.innerHeight * 0.55) style.bottom = clamp(window.innerHeight - point.y, 8, window.innerHeight - 40);
  else style.top = clamp(point.y, 8, Math.max(8, window.innerHeight - 40));
  return (0, import_react.createElement)("div", { ref, className: CLASS.menu, style, role: "menu" }, children);
}
function PetOverlay() {
  const [hostState, setHostState] = (0, import_react.useState)(null);
  const [sideId, setSideId] = (0, import_react.useState)(() => {
    const stored = readStored("size", "medium");
    return SIZE_PRESETS.some((entry) => entry.id === stored) ? stored : "medium";
  });
  const [characterId, setCharacterId] = (0, import_react.useState)(() => {
    const stored = readStored("character", "deepseek");
    return CHARACTERS.some((entry) => entry.id === stored) ? stored : "deepseek";
  });
  const [position, setPosition] = (0, import_react.useState)(() => {
    const stored = readStored("position", null);
    if (stored === null || typeof stored.left !== "number" || typeof stored.bottom !== "number") return SNAP_POSITION;
    return { left: stored.left, bottom: stored.bottom };
  });
  const [hidden, setHidden] = (0, import_react.useState)(() => readStored("hidden", false) === true);
  const [snapOnRelease, setSnapOnRelease] = (0, import_react.useState)(() => readStored("snap", true) !== false);
  const [soundOn, setSoundOn] = (0, import_react.useState)(() => readStored("sound", true) !== false);
  const [menuPoint, setMenuPoint] = (0, import_react.useState)(null);
  const [interactive, setInteractive] = (0, import_react.useState)(false);
  const [, setFrame] = (0, import_react.useState)(0);
  const [amountScale, setAmountScale] = (0, import_react.useState)(1);
  const [busy, setBusy] = (0, import_react.useState)(false);
  const modelRef = (0, import_react.useRef)(null);
  if (modelRef.current === null) modelRef.current = createModel();
  const rootRef = (0, import_react.useRef)(null);
  const amountRef = (0, import_react.useRef)(null);
  const maskRef = (0, import_react.useRef)(null);
  const rafRef = (0, import_react.useRef)(0);
  const lastTsRef = (0, import_react.useRef)(0);
  const dragRef = (0, import_react.useRef)(null);
  const lastRevisionRef = (0, import_react.useRef)(null);
  const snapNextRef = (0, import_react.useRef)(true);
  const audiosRef = (0, import_react.useRef)(null);
  const audioIndexRef = (0, import_react.useRef)(0);
  const character = (0, import_react.useMemo)(() => characterOf(characterId), [characterId]);
  const side = (0, import_react.useMemo)(() => sizeOf(sideId).side, [sideId]);
  const layout = (0, import_react.useMemo)(() => layoutOf(side), [side]);
  const soundRef = (0, import_react.useRef)(soundOn);
  const snapRef = (0, import_react.useRef)(snapOnRelease);
  const sideRef = (0, import_react.useRef)(side);
  const layoutRef = (0, import_react.useRef)(layout);
  (0, import_react.useEffect)(() => {
    soundRef.current = soundOn;
  }, [soundOn]);
  (0, import_react.useEffect)(() => {
    snapRef.current = snapOnRelease;
  }, [snapOnRelease]);
  (0, import_react.useEffect)(() => {
    sideRef.current = side;
  }, [side]);
  (0, import_react.useEffect)(() => {
    layoutRef.current = layout;
  }, [layout]);
  const model = modelRef.current;
  const connected = hostState !== null && hostState.connected === true;
  const offlineArt = character.id === "deepseek" && !connected;
  const spriteSrc = (0, import_react.useMemo)(() => assetUrl(spriteFileFor(character, connected)), [character, connected]);
  const dotColor = dotColorOf(hostState);
  const commitPosition = (0, import_react.useCallback)((next) => {
    setPosition(next);
    writeStored("position", next);
  }, []);
  (0, import_react.useEffect)(() => {
    writeStored("size", sideId);
  }, [sideId]);
  (0, import_react.useEffect)(() => {
    writeStored("character", characterId);
  }, [characterId]);
  (0, import_react.useEffect)(() => {
    writeStored("hidden", hidden);
  }, [hidden]);
  (0, import_react.useEffect)(() => {
    writeStored("snap", snapOnRelease);
  }, [snapOnRelease]);
  (0, import_react.useEffect)(() => {
    writeStored("sound", soundOn);
  }, [soundOn]);
  const playHit = (0, import_react.useCallback)(() => {
    try {
      if (audiosRef.current === null) {
        audiosRef.current = [0, 1, 2, 3].map(() => {
          const node2 = new Audio(assetUrl("hit.mp3"));
          node2.preload = "auto";
          node2.volume = 0.7;
          return node2;
        });
      }
      const pool = audiosRef.current;
      const node = pool[audioIndexRef.current % pool.length];
      audioIndexRef.current += 1;
      node.currentTime = 0;
      void node.play().catch(() => {
      });
    } catch {
    }
  }, []);
  const ensureAnimation = (0, import_react.useCallback)(() => {
    if (rafRef.current !== 0) return;
    lastTsRef.current = 0;
    const step = (timestamp) => {
      const active = modelRef.current;
      const dt = lastTsRef.current === 0 ? 0 : Math.min(0.5, (timestamp - lastTsRef.current) / 1e3);
      lastTsRef.current = timestamp;
      const hitNow = tick(active, dt);
      if (hitNow && soundRef.current) playHit();
      setFrame((value) => (value + 1) % 1e6);
      if (needsFrame(active)) rafRef.current = window.requestAnimationFrame(step);
      else {
        rafRef.current = 0;
        lastTsRef.current = 0;
      }
    };
    rafRef.current = window.requestAnimationFrame(step);
  }, [playHit]);
  (0, import_react.useEffect)(() => () => {
    if (rafRef.current !== 0) window.cancelAnimationFrame(rafRef.current);
    rafRef.current = 0;
  }, []);
  (0, import_react.useEffect)(() => {
    let alive = true;
    const pull = async () => {
      try {
        const next = await fetchState();
        if (alive) setHostState(next);
      } catch {
      }
    };
    void pull();
    const timer = window.setInterval(() => {
      void pull();
    }, POLL_INTERVAL_MS);
    return () => {
      alive = false;
      window.clearInterval(timer);
    };
  }, []);
  (0, import_react.useEffect)(() => {
    if (hostState === null) return;
    if (lastRevisionRef.current === hostState.revision) return;
    lastRevisionRef.current = hostState.revision;
    const active = modelRef.current;
    const snap = snapNextRef.current;
    snapNextRef.current = false;
    if (hostState.status === "unconfigured") resetModel(active);
    else if (typeof hostState.fen === "number") applyReading(active, hostState.fen, { snap });
    if (needsFrame(active)) ensureAnimation();
    else setFrame((value) => (value + 1) % 1e6);
  }, [hostState, ensureAnimation]);
  (0, import_react.useEffect)(() => {
    let cancelled = false;
    const image = new Image();
    image.decoding = "async";
    image.onload = () => {
      if (cancelled) return;
      try {
        const canvas = document.createElement("canvas");
        canvas.width = MASK_WIDTH;
        canvas.height = MASK_HEIGHT;
        const context = canvas.getContext("2d", { willReadFrequently: true });
        if (context === null) return;
        context.clearRect(0, 0, MASK_WIDTH, MASK_HEIGHT);
        context.drawImage(image, 0, 0, MASK_WIDTH, MASK_HEIGHT);
        maskRef.current = {
          alpha: context.getImageData(0, 0, MASK_WIDTH, MASK_HEIGHT).data,
          width: MASK_WIDTH,
          height: MASK_HEIGHT
        };
      } catch {
        maskRef.current = null;
      }
    };
    image.onerror = () => {
      maskRef.current = null;
    };
    image.src = spriteSrc;
    return () => {
      cancelled = true;
    };
  }, [spriteSrc]);
  (0, import_react.useEffect)(() => {
    if (hidden) {
      setInteractive(false);
      return void 0;
    }
    const onMove = (event) => {
      if (dragRef.current !== null) return;
      const root = rootRef.current;
      if (root === null) return;
      const rect = root.getBoundingClientRect();
      const lx = event.clientX - rect.left;
      const ly = event.clientY - rect.top;
      const boxes = layoutOf(sideRef.current);
      const inside = lx >= boxes.spriteLeft && lx <= boxes.spriteLeft + boxes.spriteWidth && ly >= boxes.spriteTop && ly <= boxes.spriteTop + boxes.spriteHeight;
      if (!inside) {
        setInteractive((previous) => previous ? false : previous);
        return;
      }
      const mask = maskRef.current;
      if (mask === null) {
        setInteractive((previous) => previous ? previous : true);
        return;
      }
      const mx = clamp(Math.floor((lx - boxes.spriteLeft) / boxes.spriteWidth * mask.width), 0, mask.width - 1);
      const my = clamp(Math.floor((ly - boxes.spriteTop) / boxes.spriteHeight * mask.height), 0, mask.height - 1);
      const alpha = mask.alpha[(my * mask.width + mx) * 4 + 3];
      const next = alpha > ALPHA_THRESHOLD;
      setInteractive((previous) => previous === next ? previous : next);
    };
    document.addEventListener("pointermove", onMove, true);
    return () => document.removeEventListener("pointermove", onMove, true);
  }, [hidden]);
  (0, import_react.useEffect)(() => {
    const onResize = () => {
      setPosition((current) => {
        const next = clampPosition(current, layoutOf(sideRef.current));
        writeStored("position", next);
        return next;
      });
    };
    window.addEventListener("resize", onResize);
    return () => window.removeEventListener("resize", onResize);
  }, []);
  const onPointerDown = (0, import_react.useCallback)((event) => {
    if (event.button !== 0) return;
    event.preventDefault();
    event.stopPropagation();
    const element = event.currentTarget;
    try {
      element.setPointerCapture(event.pointerId);
    } catch {
    }
    element.dataset.dragging = "true";
    dragRef.current = {
      pointerId: event.pointerId,
      startX: event.clientX,
      startY: event.clientY,
      originLeft: position.left,
      originBottom: position.bottom,
      // The position of the most recent pointermove, so the release commits
      // where the pet actually was dropped rather than where it started.
      last: null,
      moved: false
    };
  }, [position.left, position.bottom]);
  const onPointerMove = (0, import_react.useCallback)((event) => {
    const drag = dragRef.current;
    if (drag === null || drag.pointerId !== event.pointerId) return;
    const dx = event.clientX - drag.startX;
    const dy = event.clientY - drag.startY;
    if (!drag.moved && Math.hypot(dx, dy) < 3) return;
    drag.moved = true;
    const next = clampPosition({ left: drag.originLeft + dx, bottom: drag.originBottom - dy }, layoutRef.current);
    drag.last = next;
    setPosition(next);
  }, []);
  const onPointerUp = (0, import_react.useCallback)((event) => {
    const drag = dragRef.current;
    if (drag === null || drag.pointerId !== event.pointerId) return;
    dragRef.current = null;
    const element = event.currentTarget;
    delete element.dataset.dragging;
    try {
      element.releasePointerCapture(event.pointerId);
    } catch {
    }
    const settled = releasePosition(drag, snapRef.current);
    if (settled !== null) commitPosition(clampPosition(settled, layoutRef.current));
  }, [commitPosition]);
  const openMenu = (0, import_react.useCallback)((event) => {
    if (event !== null && event !== void 0) {
      event.preventDefault();
      event.stopPropagation();
      setMenuPoint({ x: event.clientX, y: event.clientY });
      return;
    }
    const boxes = layoutRef.current;
    setMenuPoint({ x: position.left, y: window.innerHeight - position.bottom - boxes.height });
  }, [position.left, position.bottom]);
  const closeMenu = (0, import_react.useCallback)(() => setMenuPoint(null), []);
  const runRefresh = (0, import_react.useCallback)(async () => {
    if (busy) return;
    setBusy(true);
    snapNextRef.current = true;
    try {
      setHostState(await requestRefresh());
    } catch {
      snapNextRef.current = false;
    } finally {
      setBusy(false);
    }
  }, [busy]);
  const changeInterval = (0, import_react.useCallback)(async (seconds) => {
    setBusy(true);
    try {
      setHostState(await updateSettings({ intervalSeconds: seconds }));
    } catch {
    } finally {
      setBusy(false);
    }
  }, []);
  const changeSource = (0, import_react.useCallback)(async (source) => {
    setBusy(true);
    snapNextRef.current = true;
    try {
      setHostState(await updateSettings({ source }));
    } catch {
      snapNextRef.current = false;
    } finally {
      setBusy(false);
    }
  }, []);
  const shake = shakeOffset(model, side);
  const impact2 = impact(model);
  const displayFen = displayedFen(model);
  const displayText = fenToString(displayFen);
  const amountColor = connected ? "rgb(240, 247, 255)" : "rgb(173, 186, 207)";
  const rateLimited = hostState !== null && hostState.rateLimitedUntil !== null && hostState.rateLimitedUntil > Date.now();
  (0, import_react.useLayoutEffect)(() => {
    const element = amountRef.current;
    if (element === null) return;
    const full = element.offsetWidth;
    const next = full > TABLET_WIDTH * 0.9 ? TABLET_WIDTH * 0.9 / full : 1;
    setAmountScale((previous) => Math.abs(previous - next) > 2e-3 ? next : previous);
  }, [displayText, side]);
  const petNode = hidden ? null : (0, import_react.createElement)(
    "div",
    {
      ref: rootRef,
      className: CLASS.root,
      "aria-label": `DSH \u4F59\u989D\u684C\u5BA0 \xB7 ${character.title}`,
      title: `${statusLabel(hostState)} \xB7 \u62D6\u52A8\u79FB\u52A8\uFF0C\u53F3\u952E\u6253\u5F00\u83DC\u5355`,
      style: {
        left: `${position.left}px`,
        bottom: `${position.bottom}px`,
        width: `${layout.width}px`,
        height: `${layout.height}px`,
        pointerEvents: interactive ? "auto" : "none"
      },
      onPointerDown,
      onPointerMove,
      onPointerUp,
      onPointerCancel: onPointerUp,
      onContextMenu: openMenu
    },
    model.topupTime > 0 ? (() => {
      const progress = 1 - model.topupTime / TOPUP_DURATION;
      const inset = side * (0.03 + 0.06 * (1 - progress));
      const alpha = 0.8 * (1 - progress);
      return (0, import_react.createElement)("span", {
        className: CLASS.ring,
        style: {
          left: `${layout.spriteLeft + inset}px`,
          top: `${layout.spriteTop + inset}px`,
          width: `${Math.max(0, layout.spriteWidth - inset * 2)}px`,
          height: `${Math.max(0, layout.spriteHeight - inset * 2)}px`,
          border: `${Math.max(1, side * 0.015)}px solid rgba(52, 199, 89, ${alpha.toFixed(3)})`
        }
      });
    })() : null,
    (0, import_react.createElement)(
      "div",
      {
        className: CLASS.shake,
        style: {
          left: `${layout.spriteLeft}px`,
          top: `${layout.spriteTop}px`,
          width: `${layout.spriteWidth}px`,
          height: `${layout.spriteHeight}px`,
          transform: `translate(${shake.x.toFixed(2)}px, ${shake.y.toFixed(2)}px)`
        }
      },
      (0, import_react.createElement)("img", { className: CLASS.image, src: spriteSrc, alt: "", draggable: false }),
      impact2 > 0 ? (0, import_react.createElement)("span", {
        className: CLASS.flash,
        style: {
          background: `rgba(255, 26, 36, ${(0.45 * impact2).toFixed(3)})`,
          WebkitMaskImage: `url("${spriteSrc}")`,
          maskImage: `url("${spriteSrc}")`
        }
      }) : null,
      offlineArt ? null : (0, import_react.createElement)(
        "div",
        {
          className: CLASS.tablet,
          style: {
            width: `${TABLET_WIDTH}px`,
            height: `${TABLET_HEIGHT}px`,
            // The shake layer's origin is the sprite's top-left corner, so the
            // artwork corners map into it without the canvas offset.
            transform: tabletMatrix({ spriteLeft: 0, spriteTop: 0, scale: layout.scale }, character.corners)
          }
        },
        (0, import_react.createElement)("span", {
          className: CLASS.tabletTitle,
          style: {
            top: `${TABLET_HEIGHT * 0.2}px`,
            fontSize: `${TABLET_HEIGHT * 0.21}px`,
            lineHeight: 1,
            color: "rgb(158, 184, 227)",
            transform: "translateY(-50%)"
          }
        }, "DSH \u4F59\u989D"),
        (0, import_react.createElement)(
          "span",
          {
            ref: amountRef,
            className: CLASS.tabletAmount,
            style: {
              top: `${TABLET_HEIGHT * 0.68}px`,
              transform: `translate(-50%, -50%) scale(${amountScale.toFixed(4)})`,
              color: amountColor
            }
          },
          (0, import_react.createElement)("span", { className: CLASS.tabletCurrency, style: { fontSize: `${TABLET_HEIGHT * 0.27}px` } }, "\xA5 "),
          (0, import_react.createElement)("span", { className: CLASS.tabletNumber, style: { fontSize: `${TABLET_HEIGHT * 0.48}px` } }, displayText)
        ),
        (0, import_react.createElement)("span", {
          className: CLASS.tabletDot,
          style: {
            left: `${TABLET_WIDTH * 0.92}px`,
            top: `${TABLET_HEIGHT * 0.23 - 15}px`,
            width: "15px",
            height: "15px",
            background: dotColor
          }
        })
      ),
      ...offlineArt ? [] : model.floating.map((label) => {
        const progress = Math.min(1, label.age / FLOAT_LIFETIME);
        const alpha = Math.max(0, 1 - Math.pow(progress, 1.6));
        return (0, import_react.createElement)("span", {
          key: label.id,
          className: `${CLASS.float} ${label.tone === "topup" ? CLASS.floatTopup : CLASS.floatHit}`,
          style: {
            left: `${side}px`,
            top: `${side * (0.55 - 0.45 * progress)}px`,
            fontSize: `${side * 0.08}px`,
            opacity: alpha.toFixed(3),
            transform: "translateX(-50%)",
            textShadow: `0 0 ${(side * 0.022).toFixed(2)}px rgba(0, 0, 0, ${(0.4 * alpha).toFixed(3)})`
          }
        }, label.text);
      })
    )
  );
  const menu = menuPoint === null ? null : (0, import_react.createElement)(
    MenuShell,
    { point: menuPoint, onClose: closeMenu },
    (0, import_react.createElement)(
      "div",
      { className: CLASS.menuHead },
      (0, import_react.createElement)("div", { className: CLASS.menuTitle }, statusLabel(hostState)),
      (0, import_react.createElement)(
        "div",
        { className: CLASS.menuMeta },
        hostState === null ? "\u8BFB\u53D6\u4E3B\u673A\u72B6\u6001\u2026" : hostState.source === null ? "\u51ED\u8BC1\uFF1A\u672A\u914D\u7F6E" : `\u51ED\u8BC1\uFF1A${hostState.source}${hostState.detail === null ? "" : ` \xB7 ${hostState.detail}`}`
      ),
      hostState !== null && hostState.spentDisplay !== null ? (0, import_react.createElement)("div", { className: CLASS.menuMeta }, `\u7D2F\u8BA1\u6D88\u8D39 \xA5${hostState.spentDisplay}`) : null,
      hostState !== null && hostState.error !== null ? (0, import_react.createElement)("div", { className: CLASS.menuError }, hostState.error) : null
    ),
    (0, import_react.createElement)("div", { className: CLASS.menuSep }),
    (0, import_react.createElement)(MenuItem, {
      disabled: busy || rateLimited,
      onSelect: () => {
        void runRefresh();
      }
    }, busy ? "\u5237\u65B0\u4E2D\u2026" : rateLimited ? "\u9650\u6D41\u7B49\u5F85\u4E2D\u2026" : "\u7ACB\u5373\u5237\u65B0\u4F59\u989D"),
    (0, import_react.createElement)(MenuItem, { onSelect: () => {
      playDemo(modelRef.current, 1);
      ensureAnimation();
    } }, "\u6D4B\u8BD5\u4E00\u6B21\u6263\u8D39"),
    (0, import_react.createElement)(MenuItem, { onSelect: () => {
      playDemo(modelRef.current, 5);
      ensureAnimation();
    } }, "\u6F14\u793A\u8FDE\u7EED\u6263\u8D39 \xD75"),
    (0, import_react.createElement)("div", { className: CLASS.menuSep }),
    (0, import_react.createElement)(ChipRow, {
      label: "\u89D2\u8272",
      options: CHARACTERS.map((entry) => ({ id: entry.id, title: entry.title })),
      value: characterId,
      onSelect: setCharacterId
    }),
    (0, import_react.createElement)(ChipRow, {
      label: "\u5C3A\u5BF8\uFF08\u89D2\u8272\u9AD8\u5EA6\uFF09",
      options: SIZE_PRESETS.map((entry) => ({ id: entry.id, title: `${entry.title} ${entry.side}` })),
      value: sideId,
      onSelect: setSideId
    }),
    (0, import_react.createElement)("div", { className: CLASS.menuSep }),
    (0, import_react.createElement)(MenuItem, { onSelect: () => setSnapOnRelease((value) => !value) }, snapOnRelease ? "\u2713 \u677E\u624B\u5438\u9644\u5DE6\u4E0B\u89D2" : "\u3000\u677E\u624B\u5438\u9644\u5DE6\u4E0B\u89D2"),
    (0, import_react.createElement)(MenuItem, { onSelect: () => setSoundOn((value) => !value) }, soundOn ? "\u2713 \u97F3\u6548" : "\u3000\u97F3\u6548"),
    (0, import_react.createElement)("div", { className: CLASS.menuSep }),
    (0, import_react.createElement)(ChipRow, {
      label: "\u5237\u65B0\u95F4\u9694",
      options: INTERVAL_CHOICES.map((seconds) => ({
        id: String(seconds),
        title: seconds < 60 ? `${seconds} \u79D2` : `${seconds / 60} \u5206\u949F`
      })),
      value: hostState === null ? "30" : String(hostState.intervalSeconds),
      onSelect: (id) => {
        void changeInterval(Number(id));
      }
    }),
    (0, import_react.createElement)(ChipRow, {
      label: "\u51ED\u8BC1\u6765\u6E90",
      options: SOURCE_CHOICES,
      value: hostState === null ? "auto" : hostState.sourcePreference,
      onSelect: (id) => {
        void changeSource(id);
      }
    }),
    (0, import_react.createElement)("div", { className: CLASS.menuSep }),
    (0, import_react.createElement)(MenuItem, {
      onSelect: () => {
        commitPosition(clampPosition(SNAP_POSITION, layoutRef.current));
        closeMenu();
      }
    }, "\u5438\u9644\u56DE\u5DE6\u4E0B\u89D2"),
    (0, import_react.createElement)(MenuItem, { onSelect: () => {
      setHidden(true);
      closeMenu();
    } }, "\u9690\u85CF\u684C\u5BA0")
  );
  const pillBottom = clamp(position.bottom + layout.height + 6, 8, Math.max(8, window.innerHeight - 34));
  const pillLeft = clamp(position.left, 8, Math.max(8, window.innerWidth - 130));
  const pill = (0, import_react.createElement)(
    "button",
    {
      type: "button",
      [PILL_ATTR]: "",
      className: `${CLASS.pill}${hidden ? ` ${CLASS.pillHidden}` : ""}`,
      style: { left: `${pillLeft}px`, bottom: `${pillBottom}px`, pointerEvents: "auto" },
      title: "DSH \u4F59\u989D\u684C\u5BA0 \xB7 \u70B9\u51FB\u6253\u5F00\u83DC\u5355",
      onClick: (event) => {
        event.stopPropagation();
        if (menuPoint !== null) {
          closeMenu();
          return;
        }
        const rect = event.currentTarget.getBoundingClientRect();
        setMenuPoint({ x: rect.left, y: rect.top });
      },
      onContextMenu: (event) => {
        event.preventDefault();
        setMenuPoint({ x: event.clientX, y: event.clientY });
      }
    },
    (0, import_react.createElement)("span", { className: CLASS.pillDot, style: { background: dotColor } }),
    (0, import_react.createElement)("span", null, displayFen === null ? "\xA5 --" : `\xA5 ${displayText}`),
    hidden ? (0, import_react.createElement)("span", null, "\uFF08\u5DF2\u9690\u85CF\uFF09") : null
  );
  return (0, import_react.createElement)("div", { "data-dsh-vk1-pet": "", style: { display: "contents" } }, petNode, pill, menu);
}
function apply(ctx) {
  ctx.effect(() => {
    const tag = document.createElement("style");
    tag.dataset.plugin = name;
    tag.dataset.pluginCss = STYLE_ID;
    tag.textContent = CSS;
    document.head.appendChild(tag);
    return () => {
      tag.remove();
    };
  }, "dsh-vk1-pet: styles");
  ctx.effect(
    () => ctx.slots.inject(SLOT, () => ctx.slots.register({
      name: SLOT,
      id: "vk1-pet",
      order: 50
    }, PetOverlay)),
    "dsh-vk1-pet: overlay entry"
  );
}

    return module.exports;
  },
});
